<?php
/**
 * Route DMC's canonical worktree abilities through Homeboy's native lifecycle.
 *
 * Generated by wp-coding-agents. Local edits will be overwritten.
 */

defined('ABSPATH') || exit;

final class WP_Coding_Agents_Homeboy_Worktrees {
	private const HOMEBOY = '@HOMEBOY_BINARY@';
	private const TIMEOUT_SECONDS = 120;
	private const OUTPUT_LIMIT_BYTES = 1048576;
	private const DELEGATED_ABILITIES = array(
		'datamachine-code/workspace-worktree-add',
		'datamachine-code/workspace-worktree-list',
		'datamachine-code/workspace-worktree-finalize',
		'datamachine-code/workspace-worktree-remove',
		'datamachine-code/workspace-worktree-cleanup',
	);

	/** @param array<string,mixed> $args @return array<string,mixed> */
	public static function filter_ability(array $args, string $slug): array {
		if (!in_array($slug, self::DELEGATED_ABILITIES, true)) {
			return $args;
		}

		$native_callback = $args['execute_callback'] ?? null;
		$args['execute_callback'] = static function (array $input) use ($slug, $native_callback): array|WP_Error {
			if ('datamachine-code/workspace-worktree-add' === $slug && !self::can_delegate_add($input)) {
				if (!is_callable($native_callback)) {
					return self::contract_error('DMC native worktree creation is unavailable for this request.', $input);
				}
				return call_user_func($native_callback, $input);
			}
			return self::execute($slug, $input);
		};
		$args['meta'] = array_merge(
			is_array($args['meta'] ?? null) ? $args['meta'] : array(),
			array(
				'worktree_lifecycle_owner' => 'homeboy',
				'worktree_adapter_schema'  => 'wp-coding-agents/homeboy-worktree-adapter/v1',
			)
		);
		return $args;
	}

	/** @param array<string,mixed> $input */
	private static function can_delegate_add(array $input): bool {
		if (($input['inject_context'] ?? true) || ($input['bootstrap'] ?? true)) {
			return false;
		}
		foreach (array('allow_stale', 'rebase_base', 'force', 'allow_percentage_byte_floor_exception', 'remediate_capacity', 'remediate_capacity_dry_run', 'verbose') as $unsupported) {
			if (!empty($input[$unsupported])) {
				return false;
			}
		}
		if (null !== self::optional_string($input, 'task_ref')) {
			return false;
		}
		return !isset($input['reuse_policy']) || in_array($input['reuse_policy'], array('', 'isolated'), true);
	}

	public static function adapt_cli(): void {
		$workspace_command = 'DataMachineCode\\Cli\\Commands\\WorkspaceCommand';
		if (
			!defined('WP_CLI')
			|| !WP_CLI
			|| !class_exists('WP_CLI')
			|| !class_exists($workspace_command)
			|| !method_exists($workspace_command, 'worktree_command_definitions')
			|| !method_exists($workspace_command, '__worktree_operation')
		) {
			return;
		}
		$reflection  = new \ReflectionClass($workspace_command);
		$definitions = $reflection->getMethod('worktree_command_definitions');
		$dispatcher  = $reflection->getMethod('__worktree_operation');
		$constructor = $reflection->getConstructor();
		if (
			!$reflection->isInstantiable()
			|| (null !== $constructor && 0 < $constructor->getNumberOfRequiredParameters())
			|| !self::has_exact_method_contract($definitions, true, array(), 'array')
			|| !self::has_exact_method_contract($dispatcher, false, array('string', 'array', 'array'), 'void')
		) {
			return;
		}

		try {
			$command_definitions = \DataMachineCode\Cli\Commands\WorkspaceCommand::worktree_command_definitions();
		} catch (\Throwable) {
			return;
		}
		$definition = is_array($command_definitions) ? ($command_definitions['add'] ?? null) : null;
		$synopsis   = is_array($definition) ? ($definition['synopsis'] ?? null) : null;
		if (!self::has_required_add_definition($definition, $synopsis)) {
			return;
		}
		$definition['longdesc'] = "On this Homeboy-owned runtime, context injection and dependency bootstrap are omitted by default, and native handoff freshness is always requested first. The existing --skip-context-injection and --skip-bootstrap flags remain supported aliases. Use --inject-context or --bootstrap to explicitly request DMC-owned behavior; unsupported requests return a typed refusal.\n\n" . (string) ($definition['longdesc'] ?? '');
		$definition['synopsis'] = array_merge(
			$definition['synopsis'],
			array(
				array(
					'type'        => 'flag',
					'name'        => 'inject-context',
					'description' => 'Explicitly request DMC context injection (unsupported by the Homeboy adapter).',
					'optional'    => true,
				),
				array(
					'type'        => 'flag',
					'name'        => 'bootstrap',
					'description' => 'Explicitly request DMC dependency bootstrap (unsupported by the Homeboy adapter).',
					'optional'    => true,
				),
			)
		);
		$definition['synopsis'] = array_map(
			static function (array $argument): array {
				return match ($argument['name'] ?? null) {
					'skip-context-injection' => array_merge($argument, array('description' => 'Alias confirming that Homeboy should omit DMC context injection (the adapter default).')),
					'skip-bootstrap'         => array_merge($argument, array('description' => 'Alias confirming that Homeboy should omit DMC dependency bootstrap (the adapter default).')),
					default => $argument,
				};
			},
			$definition['synopsis']
		);

		\WP_CLI::add_command(
			'datamachine-code workspace worktree add',
			static function (array $args, array $assoc_args): void {
				if (!empty($assoc_args['inject-context']) && !empty($assoc_args['skip-context-injection'])) {
					\WP_CLI::error('Use only one of --inject-context or --skip-context-injection.');
				}
				if (!empty($assoc_args['bootstrap']) && !empty($assoc_args['skip-bootstrap'])) {
					\WP_CLI::error('Use only one of --bootstrap or --skip-bootstrap.');
				}
				if (empty($assoc_args['inject-context'])) {
					$assoc_args['skip-context-injection'] = true;
				}
				if (empty($assoc_args['bootstrap'])) {
					$assoc_args['skip-bootstrap'] = true;
				}
				unset($assoc_args['inject-context'], $assoc_args['bootstrap']);
				(new \DataMachineCode\Cli\Commands\WorkspaceCommand())->__worktree_operation('add', $args, $assoc_args);
			},
			$definition
		);
	}

	/** @param list<string> $parameter_types */
	private static function has_exact_method_contract(\ReflectionMethod $method, bool $static, array $parameter_types, string $return_type): bool {
		if (!$method->isPublic() || $static !== $method->isStatic() || count($parameter_types) !== $method->getNumberOfParameters()) {
			return false;
		}
		$type = $method->getReturnType();
		if (!$type instanceof \ReflectionNamedType || $type->allowsNull() || !$type->isBuiltin() || $return_type !== $type->getName()) {
			return false;
		}
		foreach ($method->getParameters() as $index => $parameter) {
			$type = $parameter->getType();
			if (
				$parameter->isOptional()
				|| $parameter->isVariadic()
				|| $parameter->isPassedByReference()
				|| !$type instanceof \ReflectionNamedType
				|| $type->allowsNull()
				|| !$type->isBuiltin()
				|| $parameter_types[$index] !== $type->getName()
			) {
				return false;
			}
		}
		return true;
	}

	private static function has_required_add_definition(mixed $definition, mixed $synopsis): bool {
		if (!is_array($definition) || !is_string($definition['shortdesc'] ?? null) || !is_string($definition['longdesc'] ?? null) || !is_array($synopsis)) {
			return false;
		}
		$arguments = array();
		foreach ($synopsis as $argument) {
			$name = is_array($argument) ? ($argument['name'] ?? null) : null;
			if (!is_string($name) || '' === $name || isset($arguments[$name])) {
				return false;
			}
			$arguments[$name] = $argument;
		}
		$required = array(
			'repo'                   => array('type' => 'positional', 'required' => true),
			'branch'                 => array('type' => 'positional', 'required' => true),
			'skip-context-injection' => array('type' => 'flag', 'optional' => true),
			'skip-bootstrap'         => array('type' => 'flag', 'optional' => true),
		);
		foreach ($required as $name => $semantics) {
			foreach ($semantics as $key => $value) {
				if (($arguments[$name][$key] ?? null) !== $value) {
					return false;
				}
			}
		}
		return !isset($arguments['inject-context']) && !isset($arguments['bootstrap']);
	}

	/** @param array<string,mixed> $input @return array<string,mixed>|WP_Error */
	public static function execute(string $slug, array $input): array|WP_Error {
		return match ($slug) {
			'datamachine-code/workspace-worktree-add'      => self::add($input),
			'datamachine-code/workspace-worktree-list'     => self::listing($input),
			'datamachine-code/workspace-worktree-finalize' => self::finalize($input),
			'datamachine-code/workspace-worktree-remove'   => self::remove($input),
			'datamachine-code/workspace-worktree-cleanup'  => self::cleanup($input),
			default => self::refusal($slug),
		};
	}

	/** @param array<string,mixed> $input @return array<string,mixed>|WP_Error */
	private static function add(array $input): array|WP_Error {
		$repo   = self::required_string($input, 'repo');
		$branch = self::required_string($input, 'branch');
		if (is_wp_error($repo) || is_wp_error($branch)) {
			return is_wp_error($repo) ? $repo : $branch;
		}
		foreach (array('inject_context', 'bootstrap', 'allow_stale', 'rebase_base', 'force', 'allow_percentage_byte_floor_exception', 'remediate_capacity', 'remediate_capacity_dry_run', 'verbose') as $unsupported) {
			if (!empty($input[$unsupported])) {
				return self::unsupported_input($unsupported, 'Homeboy create cannot preserve this DMC-specific behavior.');
			}
		}
		if (null !== self::optional_string($input, 'task_ref')) {
			return self::unsupported_input('task_ref', 'Homeboy create accepts a canonical task URL, not a DMC task reference.');
		}
		if (!empty($input['require_task_tracker']) && null === self::optional_string($input, 'task_url')) {
			return self::unsupported_input('require_task_tracker', 'A canonical task_url is required by this request.');
		}
		if (isset($input['reuse_policy']) && !in_array($input['reuse_policy'], array('', 'isolated'), true)) {
			return self::unsupported_input('reuse_policy', 'Homeboy create allocates one exact isolated worktree identity.');
		}
		if (isset($input['cleanup_policy']) && null !== self::optional_string($input, 'cleanup_policy') && null === self::cleanup_policy($input['cleanup_policy'])) {
			return self::unsupported_input('cleanup_policy', 'Homeboy cannot represent this DMC cleanup policy.');
		}

		$command = array(self::HOMEBOY, 'worktree', 'create', self::repository_target($repo), '--branch', $branch, '--require-handoff-freshness');
		$from    = self::optional_string($input, 'from') ?? 'origin/HEAD';
		$command = array_merge($command, array('--from', $from));
		if (null !== ($task_url = self::optional_string($input, 'task_url'))) {
			$command = array_merge($command, array('--task-url', $task_url));
		}
		if (null !== ($owner = self::optional_string($input, 'owner_run_ref'))) {
			$command = array_merge($command, array('--run-id', $owner));
		}
		if (null !== ($policy = self::cleanup_policy($input['cleanup_policy'] ?? null))) {
			$command = array_merge($command, array('--cleanup-policy', $policy));
		}

		$data                     = self::homeboy($command);
		$used_unverified_fallback = false;
		if (self::is_unsupported_freshness_result($data)) {
			if (empty($input['allow_unverified_freshness'])) {
				return new WP_Error(
					'worktree_handoff_freshness_unverified',
					'Installed Homeboy cannot provide native handoff freshness. Upgrade Homeboy or explicitly permit an unverified fallback.',
					array('status' => 409, 'owner' => 'homeboy', 'retryable' => true, 'remediation' => 'upgrade_homeboy', 'cause' => 'unsupported_option')
				);
			}
			$data                     = self::homeboy(array_values(array_filter($command, static fn(string $argument): bool => '--require-handoff-freshness' !== $argument)));
			$used_unverified_fallback = true;
		}
		if (is_wp_error($data)) {
			return $data;
		}
		$record = $data['record'] ?? null;
		if (!is_array($record)) {
			return self::contract_error('Homeboy create result omitted its native worktree record.', $data);
		}
		$freshness = self::handoff_freshness($data, $record, $used_unverified_fallback);
		if (is_wp_error($freshness)) {
			return $freshness;
		}

		return array(
			'success'          => true,
			'dry_run'         => false,
			'created'         => true,
			'handle'          => (string) ($record['id'] ?? ''),
			'path'            => (string) ($record['worktree_path'] ?? ''),
			'branch'          => (string) ($record['branch'] ?? $branch),
			'base'            => (string) ($record['base_ref'] ?? $from),
			'slug'            => self::branch_slug($branch),
			'created_branch'  => true,
			'reused'          => false,
			'recycled'        => false,
			'context_injected' => false,
			'context_files'    => array(),
			'bootstrap'        => array('outcome' => 'not_requested', 'owner' => 'homeboy'),
			'handoff_freshness' => $freshness,
			'message'          => 'Homeboy owns this worktree lifecycle.',
			'metadata'         => array('homeboy' => $record),
		);
	}

	private static function repository_target(string $repo): string {
		if (!defined('DATAMACHINE_WORKSPACE_PATH')) {
			return $repo;
		}
		$root = realpath((string) DATAMACHINE_WORKSPACE_PATH);
		$path = false === $root ? false : realpath($root . DIRECTORY_SEPARATOR . $repo);
		if (false === $root || false === $path || dirname($path) !== $root || !is_dir($path) || !file_exists($path . DIRECTORY_SEPARATOR . '.git')) {
			return $repo;
		}
		return $path;
	}

	/** @param array<string,mixed> $data @param array<string,mixed> $record @return array<string,mixed>|WP_Error */
	private static function handoff_freshness(array $data, array $record, bool $allow_unverified): array|WP_Error {
		$source = $data['handoff_freshness']['proof'] ?? null;
		if (!is_array($source) || 'verified' !== ($data['handoff_freshness']['status'] ?? null)) {
			if ($allow_unverified) {
				return array('status' => 'unverified', 'reason' => 'remote_freshness_probe_unsupported');
			}
			return self::contract_error('Homeboy create result omitted required handoff freshness proof.', $data);
		}
		$proof = array(
			'version'                       => 3,
			'proof_id'                      => (string) ($source['proof_id'] ?? ''),
			'handle'                        => (string) ($record['id'] ?? ''),
			'worktree_sha'                  => (string) ($source['worktree_sha'] ?? ''),
			'resolved_base_ref'             => (string) ($source['resolved_base_ref'] ?? ''),
			'resolved_base_sha'             => (string) ($source['resolved_base_sha'] ?? ''),
			'remote_default_ref'            => (string) ($source['remote_default_ref'] ?? ''),
			'remote_default_sha'            => (string) ($source['remote_default_sha'] ?? ''),
			'remote_default_advertised_sha' => (string) ($source['remote_default_advertised_sha'] ?? ''),
			'verified_at'                   => (string) ($source['verified_at'] ?? ''),
		);
		if (in_array('', array_values($proof), true)) {
			return self::contract_error('Homeboy handoff freshness proof is incomplete.', $data);
		}
		$proof['digest'] = hash('sha256', (string) wp_json_encode(self::canonicalize($proof)));
		return array('status' => 'verified', 'proof' => $proof);
	}

	private static function canonicalize(mixed $value): mixed {
		if (!is_array($value)) {
			return $value;
		}
		foreach ($value as $key => $item) {
			$value[$key] = self::canonicalize($item);
		}
		if (array_keys($value) !== range(0, count($value) - 1)) {
			ksort($value, SORT_STRING);
		}
		return $value;
	}

	/** @param array<string,mixed> $input @return array<string,mixed>|WP_Error */
	private static function listing(array $input): array|WP_Error {
		if (!empty($input['include_disk'])) {
			return self::unsupported_input('include_disk', 'Homeboy does not expose worktree disk probes through this contract.');
		}

		$data = self::homeboy(array(self::HOMEBOY, 'worktree', 'list'));
		if (is_wp_error($data)) {
			return $data;
		}
		$records = is_array($data['worktrees'] ?? null) ? $data['worktrees'] : array();
		$rows    = array();
		foreach ($records as $record) {
			if (!is_array($record) || !self::record_matches($record, $input)) {
				continue;
			}
			$rows[] = self::record_row($record, !empty($input['include_status']));
		}
		foreach ($rows as $row) {
			if (is_wp_error($row)) {
				return $row;
			}
		}

		usort($rows, static fn(array $left, array $right): int => strcmp($left['handle'], $right['handle']));
		$limit  = !empty($input['all']) ? max(1, count($rows)) : max(1, min(200, (int) ($input['limit'] ?? 50)));
		$matching_total = count($rows);
		$cursor         = self::optional_string($input, 'cursor');
		if (null !== $cursor) {
			$decoded = base64_decode($cursor, true);
			if (false === $decoded) {
				return self::unsupported_input('cursor', 'The Homeboy worktree cursor is malformed.');
			}
			$rows = array_values(array_filter($rows, static fn(array $row): bool => strcmp($row['handle'], $decoded) > 0));
		}
		$remaining   = count($rows);
		$page        = array_slice($rows, 0, $limit);
		$next_cursor = $remaining > count($page) ? base64_encode((string) $page[count($page) - 1]['handle']) : null;

		return array(
			'success'          => true,
			'total'            => $matching_total,
			'returned'         => count($page),
			'next_cursor'      => $next_cursor,
			'status_requested' => !empty($input['include_status']),
			'disk_requested'   => false,
			'partial'          => null !== $next_cursor,
			'fields_skipped'   => !empty($input['include_status']) ? array('disk') : array('status', 'disk'),
			'summary'          => array('owner' => 'homeboy', 'matching' => $matching_total),
			'worktrees'        => $page,
			'duplicates'       => array(),
		);
	}

	/** @param array<string,mixed> $record @return array<string,mixed>|WP_Error */
	private static function record_row(array $record, bool $include_status): array|WP_Error {
		$handle = (string) ($record['id'] ?? '');
		$safety = null;
		if ($include_status) {
			$status = self::homeboy(array(self::HOMEBOY, 'worktree', 'status', $handle));
			if (is_wp_error($status)) {
				return $status;
			}
			$safety = is_array($status['safety'] ?? null) ? $status['safety'] : array();
		}

		$task_url = self::optional_string($record, 'task_url');
		return array(
			'handle'          => $handle,
			'repo'            => (string) ($record['component_id'] ?? ''),
			'is_worktree'     => true,
			'is_primary'      => false,
			'external'        => false,
			'branch_slug'     => self::branch_slug((string) ($record['branch'] ?? '')),
			'branch'          => $record['branch'] ?? null,
			'head'            => '',
			'path'            => (string) ($record['worktree_path'] ?? ''),
			'dirty'           => null === $safety ? null : (!empty($safety['dirty']) ? 1 : 0),
			'created_at'      => $record['created_at'] ?? null,
			'lifecycle_state' => self::dmc_state($record),
			'liveness'        => empty($record['terminal_disposition']) ? 'unknown' : 'stopped',
			'liveness_reason' => empty($record['terminal_disposition']) ? 'homeboy_owner_state' : 'homeboy_terminal_disposition',
			'owner'           => array('site' => 'unknown', 'site_url' => null, 'agent' => 'homeboy', 'user' => 'unknown'),
			'session'         => array('primary_id' => $record['run_id'] ?? null, 'ids' => array()),
			'task'            => null === $task_url ? null : array('task_url' => $task_url),
			'metadata'        => array('homeboy' => $record, 'homeboy_safety' => $safety),
			'fields_skipped'  => null === $safety ? array('status', 'disk') : array('disk'),
		);
	}

	/** @param array<string,mixed> $input @return array<string,mixed>|WP_Error */
	private static function finalize(array $input): array|WP_Error {
		$handle = self::required_string($input, 'handle');
		$state  = self::required_string($input, 'state');
		if (is_wp_error($handle) || is_wp_error($state)) {
			return is_wp_error($handle) ? $handle : $state;
		}
		if (null !== self::optional_string($input, 'pr')) {
			return self::unsupported_input('pr', 'Homeboy terminal finalization does not persist DMC PR metadata.');
		}
		$disposition = match ($state) {
			'merged', 'cleanup_eligible' => 'succeeded',
			'closed'                    => 'cancelled',
			'abandoned'                 => 'failed',
			default                     => null,
		};
		if (null === $disposition) {
			return self::unsupported_input('state', 'Homeboy finalization accepts terminal DMC lifecycle states only.');
		}

		$status = self::homeboy(array(self::HOMEBOY, 'worktree', 'status', $handle));
		if (is_wp_error($status)) {
			return $status;
		}
		$record = is_array($status['record'] ?? null) ? $status['record'] : array();
		$owner  = self::optional_string($record, 'run_id');
		if (null === $owner) {
			return self::unsupported_input('owner_run_ref', 'The Homeboy worktree has no exact owner-run reference for finalization.');
		}

		$data = self::homeboy(array(self::HOMEBOY, 'worktree', 'finalize', $handle, '--owner-run-ref', $owner, '--disposition', $disposition));
		if (is_wp_error($data)) {
			return $data;
		}
		return array(
			'success'         => true,
			'handle'          => $handle,
			'path'            => (string) ($data['inspection_path'] ?? $record['worktree_path'] ?? ''),
			'lifecycle_state' => $state,
			'metadata'        => array('homeboy' => $data, 'owner_run_ref' => $owner),
			'message'         => 'Homeboy recorded the terminal disposition without cleanup.',
		);
	}

	/** @param array<string,mixed> $input @return array<string,mixed>|WP_Error */
	private static function remove(array $input): array|WP_Error {
		$repo   = self::required_string($input, 'repo');
		$branch = self::required_string($input, 'branch');
		if (is_wp_error($repo) || is_wp_error($branch)) {
			return is_wp_error($repo) ? $repo : $branch;
		}
		$handle  = $repo . '@' . self::branch_slug($branch);
		$command = array(self::HOMEBOY, 'worktree', 'remove', $handle);
		if (!empty($input['force'])) {
			$command[] = '--force';
		}
		$data = self::homeboy($command);
		if (is_wp_error($data)) {
			return $data;
		}
		return array('success' => true, 'handle' => $handle, 'message' => 'Homeboy removed the worktree after native safety checks.', 'homeboy' => $data);
	}

	/** @param array<string,mixed> $input @return array<string,mixed>|WP_Error */
	private static function cleanup(array $input): array|WP_Error {
		foreach (array('skip_github', 'inventory_only', 'apply_plan', 'older_than', 'sort', 'include_repaired_metadata', 'limit', 'offset', 'until_budget') as $unsupported) {
			if (array_key_exists($unsupported, $input) && !in_array($input[$unsupported], array(false, null, ''), true)) {
				return self::unsupported_input($unsupported, 'Homeboy cleanup cannot preserve this DMC-specific option.');
			}
		}
		$dry_run = !empty($input['dry_run']);
		$command = array(self::HOMEBOY, 'worktree', 'cleanup');
		if (!$dry_run) {
			$command[] = '--apply';
		}
		if (!empty($input['force'])) {
			$command[] = '--force';
		}
		$data = self::homeboy($command);
		if (is_wp_error($data)) {
			return $data;
		}
		$worktrees = is_array($data['worktrees'] ?? null) ? $data['worktrees'] : array();
		return array(
			'success'    => true,
			'dry_run'    => (bool) ($worktrees['dry_run'] ?? $dry_run),
			'candidates' => is_array($worktrees['candidates'] ?? null) ? $worktrees['candidates'] : array(),
			'removed'    => is_array($worktrees['removed'] ?? null) ? $worktrees['removed'] : array(),
			'skipped'    => is_array($worktrees['skipped'] ?? null) ? $worktrees['skipped'] : array(),
			'summary'    => is_array($worktrees['counts'] ?? null) ? $worktrees['counts'] : array(),
		);
	}

	/** @param array<string,mixed> $record @param array<string,mixed> $input */
	private static function record_matches(array $record, array $input): bool {
		if ('removed' === ($record['state'] ?? null)) {
			return false;
		}
		$matches = array(
			'repo'          => $record['component_id'] ?? null,
			'handle'        => $record['id'] ?? null,
			'owner_run_ref' => $record['run_id'] ?? null,
			'state'         => self::dmc_state($record),
		);
		foreach ($matches as $field => $value) {
			if (null !== ($expected = self::optional_string($input, $field)) && $expected !== $value) {
				return false;
			}
		}
		$task = self::optional_string($input, 'task_ref');
		return null === $task || $task === ($record['task_url'] ?? null);
	}

	/** @param list<string> $command @return array<string,mixed>|WP_Error */
	private static function homeboy(array $command): array|WP_Error {
		$result = self::run($command);
		if (is_wp_error($result)) {
			return $result;
		}
		$stdout = $result['stdout'];
		$stderr = $result['stderr'];
		$exit   = $result['exit_code'];

		$payload = json_decode($stdout, true);
		if (2 === $exit && str_contains($stderr, "unexpected argument '--require-handoff-freshness' found")) {
			return new WP_Error(
				'wp_coding_agents_homeboy_worktree_unsupported_option',
				'Installed Homeboy does not support required handoff freshness.',
				array('status' => 409, 'owner' => 'homeboy', 'option' => '--require-handoff-freshness', 'retryable' => false)
			);
		}
		if (!is_array($payload) || 'homeboy/command-result/v3' !== ($payload['schema'] ?? null)) {
			return self::contract_error('Homeboy returned malformed command-result JSON.', array('exit_code' => $exit, 'stderr' => trim($stderr)));
		}
		if (0 !== $exit || empty($payload['success'])) {
			return new WP_Error(
				'wp_coding_agents_homeboy_worktree_failed',
				(string) ($payload['diagnostics']['message'] ?? $payload['summary'] ?? 'Homeboy worktree operation failed.'),
				array('status' => 409, 'owner' => 'homeboy', 'homeboy' => $payload)
			);
		}
		return is_array($payload['data'] ?? null) ? $payload['data'] : array();
	}

	private static function is_unsupported_freshness_result(array|WP_Error $result): bool {
		return is_wp_error($result)
			&& 'wp_coding_agents_homeboy_worktree_unsupported_option' === $result->get_error_code()
			&& '--require-handoff-freshness' === ($result->get_error_data()['option'] ?? null);
	}

	/** @param list<string> $command @return array{stdout:string,stderr:string,exit_code:int}|WP_Error */
	private static function run(array $command): array|WP_Error {
		$descriptors = array(1 => array('pipe', 'w'), 2 => array('pipe', 'w'));
		$process = proc_open($command, $descriptors, $pipes, null, null, array('bypass_shell' => true));
		if (!is_resource($process)) {
			return self::contract_error('Homeboy process could not be started.', array());
		}
		stream_set_blocking($pipes[1], false);
		stream_set_blocking($pipes[2], false);
		$stdout = '';
		$stderr = '';
		$start  = microtime(true);
		$exit   = null;
		do {
			$stdout .= (string) stream_get_contents($pipes[1]);
			$stderr .= (string) stream_get_contents($pipes[2]);
			if (strlen($stdout) + strlen($stderr) > self::OUTPUT_LIMIT_BYTES) {
				proc_terminate($process, 9);
				self::close_process($process, $pipes);
				return self::contract_error('Homeboy output exceeded the bounded adapter limit.', array());
			}
			$status = proc_get_status($process);
			if (!$status['running']) {
				$exit = (int) $status['exitcode'];
				break;
			}
			if (microtime(true) - $start >= self::TIMEOUT_SECONDS) {
				proc_terminate($process, 9);
				self::close_process($process, $pipes);
				return self::contract_error('Homeboy exceeded the bounded adapter timeout.', array());
			}
			usleep(10000);
		} while (true);
		$stdout .= (string) stream_get_contents($pipes[1]);
		$stderr .= (string) stream_get_contents($pipes[2]);
		if (strlen($stdout) + strlen($stderr) > self::OUTPUT_LIMIT_BYTES) {
			self::close_process($process, $pipes);
			return self::contract_error('Homeboy output exceeded the bounded adapter limit.', array());
		}
		self::close_process($process, $pipes);
		return array('stdout' => $stdout, 'stderr' => $stderr, 'exit_code' => $exit ?? -1);
	}

	/** @param resource $process @param array<int,resource> $pipes */
	private static function close_process($process, array $pipes): void {
		foreach ($pipes as $pipe) {
			fclose($pipe);
		}
		proc_close($process);
	}

	/** @param array<string,mixed> $input @return string|WP_Error */
	private static function required_string(array $input, string $field): string|WP_Error {
		$value = self::optional_string($input, $field);
		return null === $value ? self::unsupported_input($field, "A non-empty {$field} is required.") : $value;
	}

	/** @param array<string,mixed> $input */
	private static function optional_string(array $input, string $field): ?string {
		return isset($input[$field]) && is_scalar($input[$field]) && '' !== trim((string) $input[$field]) ? trim((string) $input[$field]) : null;
	}

	private static function cleanup_policy(mixed $value): ?string {
		return match ($value) {
			// Without an owner-bound successful finalization, preserve-on-failure
			// remains ineligible for cleanup and therefore preserves DMC manual intent.
			'manual'              => 'preserve-on-failure',
			'remove_on_success'   => 'remove-when-safe',
			'preserve_on_failure' => 'preserve-on-failure',
			default               => null,
		};
	}

	/** @param array<string,mixed> $record */
	private static function dmc_state(array $record): ?string {
		return match ($record['terminal_disposition'] ?? null) {
			'succeeded' => 'cleanup_eligible',
			'failed'    => 'abandoned',
			'cancelled' => 'closed',
			default     => match ($record['state'] ?? null) {
				'completed' => 'cleanup_eligible',
				default     => $record['state'] ?? null,
			},
		};
	}

	private static function branch_slug(string $branch): string {
		return trim((string) preg_replace('/[^A-Za-z0-9_-]+/', '-', $branch), '-');
	}

	private static function refusal(string $slug): WP_Error {
		return new WP_Error(
			'wp_coding_agents_homeboy_worktree_unsupported',
			'This DMC worktree operation has no exact Homeboy lifecycle equivalent.',
			array('status' => 409, 'ability' => $slug, 'owner' => 'homeboy', 'retryable' => false)
		);
	}

	private static function unsupported_input(string $field, string $message): WP_Error {
		return new WP_Error('wp_coding_agents_homeboy_worktree_unsupported_input', $message, array('status' => 400, 'field' => $field, 'owner' => 'homeboy', 'retryable' => false));
	}

	/** @param array<string,mixed> $evidence */
	private static function contract_error(string $message, array $evidence): WP_Error {
		return new WP_Error('wp_coding_agents_homeboy_worktree_contract_error', $message, array('status' => 500, 'owner' => 'homeboy', 'evidence' => $evidence));
	}
}

add_filter('datamachine_code_ability_registration_args', array(WP_Coding_Agents_Homeboy_Worktrees::class, 'filter_ability'), 10, 2);
add_action('plugins_loaded', array(WP_Coding_Agents_Homeboy_Worktrees::class, 'adapt_cli'), 22);
